package com.hyoguoo.paymentplatform.mock;

import com.hyoguoo.paymentplatform.payment.application.port.PaymentEventRepository;
import com.hyoguoo.paymentplatform.payment.domain.PaymentEvent;
import com.hyoguoo.paymentplatform.payment.domain.PaymentOrder;
import com.hyoguoo.paymentplatform.payment.domain.enums.PaymentEventStatus;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumMap;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.test.util.ReflectionTestUtils;

public class FakePaymentEventRepository implements PaymentEventRepository {

    private final Map<Long, PaymentEvent> paymentEventDatabase = new HashMap<>();
    private final Map<Long, List<PaymentOrder>> paymentOrderDatabase = new HashMap<>();
    private Long autoGeneratedEventId = 1L;
    private Long autoGeneratedOrderId = 1L;

    @Override
    public Optional<PaymentEvent> findById(Long id) {
        Optional<PaymentEvent> paymentEvent = Optional.ofNullable(paymentEventDatabase.get(id));
        paymentEvent.ifPresent(event -> event.addPaymentOrderList(findPaymentOrdersByPaymentEventId(event.getId())));

        return paymentEvent;
    }

    @Override
    public Optional<PaymentEvent> findByOrderId(String orderId) {
        Optional<PaymentEvent> paymentEvent = paymentEventDatabase.values().stream()
                .filter(event -> event.getOrderId().equals(orderId))
                .findFirst();
        paymentEvent.ifPresent(event -> event.addPaymentOrderList(findPaymentOrdersByPaymentEventId(event.getId())));

        return paymentEvent;
    }

    @Override
    public PaymentEvent saveOrUpdate(PaymentEvent paymentEvent) {
        if (paymentEvent.getId() == null) {
            ReflectionTestUtils.setField(paymentEvent, "id", autoGeneratedEventId);
            autoGeneratedEventId++;
        }

        paymentEventDatabase.put(paymentEvent.getId(), paymentEvent);
        paymentOrderDatabase.put(paymentEvent.getId(), new ArrayList<>(paymentEvent.getPaymentOrderList()));

        if (!paymentEvent.getPaymentOrderList().isEmpty()) {
            savePaymentOrders(paymentEvent.getId(), paymentEvent.getPaymentOrderList());
        }

        return paymentEvent;
    }

    @Override
    public List<PaymentEvent> findDelayedInProgressOrUnknownEvents(LocalDateTime before) {
        List<PaymentEvent> paymentEventList = paymentEventDatabase.values().stream()
                .filter(
                        event ->
                                event.getStatus() == PaymentEventStatus.UNKNOWN ||
                                        (event.getStatus() == PaymentEventStatus.IN_PROGRESS
                                                && event.getExecutedAt().isBefore(before))
                )
                .toList();
        paymentEventList.forEach(event -> event.addPaymentOrderList(findPaymentOrdersByPaymentEventId(event.getId())));

        return paymentEventList;
    }

    @Override
    public List<PaymentEvent> findReadyPaymentsOlderThan(LocalDateTime before) {
        List<PaymentEvent> paymentEventList = paymentEventDatabase.values().stream()
                .filter(event ->
                        event.getStatus() == PaymentEventStatus.READY &&
                                event.getCreatedAt() != null &&
                                event.getCreatedAt().isBefore(before)
                )
                .toList();
        paymentEventList.forEach(event -> event.addPaymentOrderList(findPaymentOrdersByPaymentEventId(event.getId())));

        return paymentEventList;
    }

    public void savePaymentOrders(Long paymentEventId, List<PaymentOrder> paymentOrders) {
        paymentOrderDatabase.put(paymentEventId, assignIdsToPaymentOrders(paymentOrders));
    }

    private List<PaymentOrder> assignIdsToPaymentOrders(List<PaymentOrder> paymentOrders) {
        return paymentOrders.stream()
                .peek(paymentOrder -> {
                    if (paymentOrder.getId() == null) {
                        ReflectionTestUtils.setField(paymentOrder, "id", autoGeneratedOrderId);
                        autoGeneratedOrderId++;
                    }
                })
                .toList();
    }

    public List<PaymentOrder> findPaymentOrdersByPaymentEventId(Long paymentEventId) {
        return paymentOrderDatabase.getOrDefault(paymentEventId, Collections.emptyList());
    }

    @Override
    public Map<PaymentEventStatus, Long> countByStatus() {
        Map<PaymentEventStatus, Long> statusCounts = new EnumMap<>(PaymentEventStatus.class);
        for (PaymentEvent event : paymentEventDatabase.values()) {
            statusCounts.merge(event.getStatus(), 1L, Long::sum);
        }
        return statusCounts;
    }

    @Override
    public long countByStatusAndExecutedAtBefore(PaymentEventStatus status, LocalDateTime before) {
        return paymentEventDatabase.values().stream()
                .filter(event -> event.getStatus() == status &&
                        event.getExecutedAt() != null &&
                        event.getExecutedAt().isBefore(before))
                .count();
    }

    @Override
    public long countByRetryCountGreaterThanEqual(int retryCount) {
        return paymentEventDatabase.values().stream()
                .filter(event -> event.getRetryCount() >= retryCount)
                .count();
    }

    @Override
    public Map<PaymentEventStatus, Map<String, Long>> countByStatusAndAgeBuckets(
            LocalDateTime fiveMinutesAgo,
            LocalDateTime thirtyMinutesAgo
    ) {
        Map<PaymentEventStatus, Map<String, Long>> result = new EnumMap<>(PaymentEventStatus.class);

        for (PaymentEvent event : paymentEventDatabase.values()) {
            String ageBucket;
            if (event.getLastStatusChangedAt().isAfter(fiveMinutesAgo) ||
                    event.getLastStatusChangedAt().isEqual(fiveMinutesAgo)) {
                ageBucket = "recent";
            } else if (event.getLastStatusChangedAt().isAfter(thirtyMinutesAgo) ||
                    event.getLastStatusChangedAt().isEqual(thirtyMinutesAgo)) {
                ageBucket = "medium";
            } else {
                ageBucket = "old";
            }

            result.computeIfAbsent(event.getStatus(), k -> new HashMap<>())
                    .merge(ageBucket, 1L, Long::sum);
        }

        return result;
    }

    @Override
    public long countNearExpiration(LocalDateTime expirationThreshold) {
        return paymentEventDatabase.values().stream()
                .filter(event -> event.getStatus() == PaymentEventStatus.READY &&
                        event.getCreatedAt() != null &&
                        event.getCreatedAt().isBefore(expirationThreshold))
                .count();
    }
}
