#!/usr/bin/env python3
"""공통 역할 정의에서 Claude/Codex 설정 생성. --check는 변경 없이 불일치를 검출한다."""

import argparse
import json
from pathlib import Path
import re
import sys
import tomllib

REPO_ROOT = Path(__file__).resolve().parent.parent


def quote(value):
    # JSON 문자열은 이 파일에서 사용하는 YAML/TOML 기본 문자열과 호환된다.
    return json.dumps(value, ensure_ascii=False)


def render_configs(root):
    manifest = tomllib.loads((root / ".agents/roles.toml").read_text(encoding="utf-8"))
    outputs = {}
    for name, role in manifest["roles"].items():
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name):
            raise ValueError(f"잘못된 역할 이름: {name}")
        source = (root / role["instructions"]).resolve()
        if not source.is_relative_to((root / ".agents/roles").resolve()):
            raise ValueError(f"공통 역할 디렉토리 밖 경로: {source}")
        body = source.read_text(encoding="utf-8").strip()
        if not body:
            raise ValueError(f"역할 본문이 비어 있음: {source}")
        instructions = (
            f"공통 역할 정본: `{role['instructions']}`. "
            "이 파일은 scripts/sync-agent-configs.py로 생성한다.\n\n" + body + "\n"
        )
        claude_fields = {
            "name": name,
            "description": role["description"],
            "model": role["claude_model"],
            "effort": role["claude_effort"],
            "tools": role["claude_tools"],
            "color": role["claude_color"],
        }
        outputs[root / f".claude/agents/{name}.md"] = (
            "---\n" + "".join(f"{key}: {quote(value)}\n" for key, value in claude_fields.items())
            + "---\n\n" + instructions
        )
        codex_fields = {
            "name": name,
            "description": role["description"],
            "model": role["codex_model"],
            "model_reasoning_effort": role["codex_effort"],
            "developer_instructions": instructions,
        }
        if "codex_sandbox_mode" in role:
            codex_fields["sandbox_mode"] = role["codex_sandbox_mode"]
        outputs[root / f".codex/agents/{name}.toml"] = (
            "# Generated by scripts/sync-agent-configs.py; edit .agents/roles.toml or .agents/roles/.\n"
            + "".join(f"{key} = {quote(value)}\n" for key, value in codex_fields.items())
        )
    return outputs


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="생성 없이 불일치 검사")
    args = parser.parse_args(argv)
    outputs = render_configs(REPO_ROOT)
    mismatches = []
    for path, content in outputs.items():
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            continue
        if args.check:
            mismatches.append(path.relative_to(REPO_ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    # 이전 역할 삭제·이름 변경은 자동으로 파일을 지우지 않고 정리가 필요한 경로를 보고한다.
    extras = [
        p.relative_to(REPO_ROOT)
        for directory, pattern in [(".claude/agents", "*.md"), (".codex/agents", "*.toml")]
        for p in (REPO_ROOT / directory).glob(pattern)
        if p not in outputs and any(marker in p.read_text(encoding="utf-8") for marker in (
            "Generated by scripts/sync-agent-configs.py", "scripts/sync-agent-configs.py로 생성"
        ))
    ]
    if mismatches or extras:
        for path in mismatches:
            print(f"설정 불일치: {path}")
        for path in extras:
            print(f"정본에 없는 생성 파일: {path}")
        return 1
    print(f"에이전트 설정 {len(outputs)}개 {'동기화 확인' if args.check else '생성/동기화 완료'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
